services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=DotnetApiDocker;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;Connect Timeout=30
    networks:
      - dotnet-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "14330:1433"
    networks:
      - dotnet-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 60s
      timeout: 45s
      retries: 5
      start_period: 120s
    volumes:
      - sqldata:/var/opt/mssql

networks:
  dotnet-network:
    driver: bridge

volumes:
  sqldata:
